export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "surface-container-high": "#ebe8e1",
        "primary-fixed": "#cbe9dd",
        "on-secondary-fixed": "#042100",
        "inverse-on-surface": "#f3f0e9",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ccee9c",
        "inverse-primary": "#afcdc1",
        "tertiary-container": "#2f4908",
        "inverse-surface": "#31312c",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#314c43",
        "on-tertiary-container": "#99b96c",
        "primary-fixed-dim": "#afcdc1",
        "on-primary-container": "#97b5a9",
        "on-secondary-container": "#1f7203",
        "primary": "#153128",
        "on-surface": "#1c1c18",
        "on-background": "#1c1c18",
        "surface-dim": "#dcdad3",
        "on-primary-fixed": "#042018",
        "surface": "#fcf9f2",
        "secondary": "#1b6d00",
        "surface-tint": "#48645a",
        "surface-bright": "#fcf9f2",
        "secondary-fixed": "#a0f880",
        "on-secondary-fixed-variant": "#125200",
        "secondary-container": "#9df57d",
        "on-primary": "#ffffff",
        "surface-container": "#f1eee7",
        "on-error-container": "#93000a",
        "background": "#fcf9f2",
        "error": "#ba1a1a",
        "outline": "#727975",
        "surface-container-highest": "#e5e2db",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#85db67",
        "outline-variant": "#c1c8c4",
        "on-tertiary-fixed-variant": "#344e0e",
        "surface-variant": "#e5e2db",
        "primary-container": "#2c473e",
        "on-surface-variant": "#424845",
        "error-container": "#ffdad6",
        "surface-container-low": "#f6f3ec",
        "tertiary": "#1d3100",
        "tertiary-fixed-dim": "#b0d182",
        "on-tertiary-fixed": "#112000"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
